### ISSUE TITLE
Change position of close button in navigation menu

### ISSUE THREAD

**Issue by Kaybangz** [Judge-Paul/jobwrite-ai#15]
## Description
When in mobile view, the close button icon for the navigation menu is positioned at the bottom. I think it would be better to put it in the same position as the hamburger menu icon

![CoverWriteAI - Google Chrome 9_5_2023 2_12_31 PM](https://github.com/Judge-Paul/coverwrite-ai/assets/89660871/779cf5f0-8d31-47ca-81f8-c8516d8eaded)

**Comment by Judge-Paul** [comment]
@Kaybangz No it will ruin the current design except you want to change the complete design and make the navbar show while it's open on mobile view
