### ISSUE TITLE
bug: stop form from submitting when clearing skills

### ISSUE THREAD

**Issue by Judge-Paul** [Judge-Paul/jobwrite-ai#17]
## Description

Sometimes the form is going to submit when you try to remove multiple skills. Identify the problem, come up with a solution and make a PR

## Expected Behavior
The skill should just be deleted without submitting the form
![Untitled design(1)](https://github.com/Judge-Paul/coverwrite-ai/assets/110723341/1b149eaf-c7c5-455d-9da6-2f374cc9d602)

## Current Behavior
The form is being submitted when you remove multiple skills (This happens sometimes and doesn't happen other times)
![Untitled design](https://github.com/Judge-Paul/coverwrite-ai/assets/110723341/d35c1030-317e-41be-a95a-38d30b56272d)

## Steps to Reproduce
Add some skills to the skills input and try removing them

- [x] I have searched for similar issues before opening this one.
- [x] I have read and understand the [CONTRIBUTING.md](./CONTRIBUTING.md) document.

**Comment by Shivam-Sharma-1** [comment]
I would like to fix this.
Please assign it to me.

**Comment by Judge-Paul** [comment]
@Shivam-Sharma-1 Sure

**Comment by Shivam-Sharma-1** [comment]
@Judge-Paul The issue has been resolved by me :)
