### ISSUE TITLE
[Enhancement]   Cover Letter template improvment.

### ISSUE THREAD

**Issue by Sankalpa-Acharya** [Judge-Paul/jobwrite-ai#20]
## Description

I have changed the font and font size to make it look good. We can also create a custom template so that the user can have a good UI Cover letter.

**Comment by Judge-Paul** [comment]
Please can you add a screenshot or a link to the fork you made

**Comment by Sankalpa-Acharya** [comment]
I just made a PR you can review it. For now, I have just changed the font.
