### ISSUE TITLE
Add Sample Cover letter

### ISSUE THREAD

**Issue by SaumyaSubham** [Judge-Paul/jobwrite-ai#26]
I want to add another sample cover letter for Data Scientist in the examples section.
Kindly assign me this issue under hacktoberfest 2024.

**Comment by Judge-Paul** [comment]
Hey @SaumyaSubham ,

Thanks for your interest in contributin but tbh there isn't really a need as that secton would soon be taken off the site
 
 I'm open to other possible contributions tho
