### ISSUE TITLE
create examples

### ISSUE THREAD

**Issue by Judge-Paul** [Judge-Paul/jobwrite-ai#4]
## Description

For this you can test run the site and create example cover letters record it and create an example page where you'll add this video so users can see it and understand how the site works.

## Checklist

- [x] I have searched for similar issues before opening this one.
- [x] I have read and understand the [CONTRIBUTING.md](./CONTRIBUTING.md) document.

**Comment by GrandeMan** [comment]
Hey, is anyone working on this feature?

**Comment by Judge-Paul** [comment]
> Hey, is anyone working on this feature?

No one's working on it,

It's all yours.
