### ISSUE TITLE
Documentation help

### ISSUE THREAD

**Issue by Judge-Paul** [Judge-Paul/jobwrite-ai#5]
Help me write better documentation for the [issues](https://github.com/Judge-Paul/coverwrite-ai/blob/main/.github/ISSUE_TEMPLATE.md) and [pull request](https://github.com/Judge-Paul/coverwrite-ai/blob/main/.github/PULL_REQUEST_TEMPLATE.md) templates

**Comment by Heccubernny** [comment]
Can I be assigned to this

**Comment by Judge-Paul** [comment]
@Heccubernny done

**Comment by Heccubernny** [comment]
Thanks, I will work on it

**Comment by Judge-Paul** [comment]
Hey @Heccubernny how's this going?

**Comment by Heccubernny** [comment]
about to work on it now. been task with something before.

**Comment by Judge-Paul** [comment]
@Heccubernny You didn't add the pull request template

**Comment by Heccubernny** [comment]
Okay will add that, thanks for the feedback
