### ISSUE TITLE
[bug] Examples and About section is showing page error.

### ISSUE THREAD

**Issue by Rishav1707** [Judge-Paul/jobwrite-ai#6]
## Description

- Examples and About section is showing a page error.

## Expected Behavior

- It should be showing examples of the cover letter.
- It should be showing the About section of CoverWriteAI.

## Current Behavior

- It shows `the page you are looking for does not exist`.

## Steps to Reproduce

- Go to https://coverwrite.vercel.app/examples
- See the error on the screen.

## Screenshots (if applicable)

![CoverWriteAI - Google Chrome 22-08-2023 19_53_28](https://github.com/Judge-Paul/coverwrite-ai/assets/97666287/29668b3d-c53a-4687-90a8-c7f0e206e24a)

## Checklist

- [x] I have searched for similar issues before opening this one.
- [x] I have read and understand the [CONTRIBUTING.md](./CONTRIBUTING.md) document.

**Comment by Judge-Paul** [comment]
Yh, I haven't created the pages yet and I don't think I will for a while if you're feeling up to it you can create an examples page and send a PR

**Comment by Rishav1707** [comment]
> Yh, I haven't created the pages yet and I don't think I will for a while if you're feeling up to it you can create an examples page and send a PR

Sure @Judge-Paul

**Comment by Judge-Paul** [comment]
> > Yh, I haven't created the pages yet and I don't think I will for a while if you're feeling up to it you can create an examples page and send a PR
> 
> Sure @Judge-Paul 

You're going to work on it?

**Comment by OlushesiToheeb** [comment]
Hi @Judge-Paul, I'd like to jump on this. Kindly assign this to me also can you elaborate on and what will be on the example page, I'm sure the About page will be about the app right?

**Comment by Judge-Paul** [comment]
Hey @OlushesiToheeb, I don't really have a specific design in mind yet, the About page should just have some information about the site, how it works, mention the fact that it's powered by Google's PaLM API and the example page can just be a recording of the site being used.

**Comment by Judge-Paul** [comment]
@OlushesiToheeb also you can submit two PRs for this

**Comment by OlushesiToheeb** [comment]
@Judge-Paul do we store the records of the site being used somewhere?

**Comment by Judge-Paul** [comment]
@OlushesiToheeb What records? Each created Cover Letter?

**Comment by OlushesiToheeb** [comment]
yea @Judge-Paul that we can use for the example page, according to what you said [here](https://github.com/Judge-Paul/coverwrite-ai/issues/6#issuecomment-1749953730)

**Comment by Judge-Paul** [comment]
@OlushesiToheeb No we don't have any records, if you can screen record using the site that will be great otherwise you can create only the about page.
